# ===================================================================
# SECRET KEYS & CREDENTIALS CONFIGURATION
# ===================================================================


app.secrets.database.username=root
app.secrets.database.password=

# Redis Password (để trống nếu không đặt mật khẩu)
app.secrets.redis.password=

# RabbitMQ Credentials
app.secrets.rabbitmq.username=guest
app.secrets.rabbitmq.password=guest

# JWT Secret & Expiration
app.secrets.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.secrets.jwt.access-token-expiration-ms=1800000
app.secrets.jwt.refresh-token-expiration-ms=604800000

# AWS S3 / Cloudflare R2 Credentials
app.secrets.storage.access-key=8ac71e4eb8ff67a7023f717a7b361cf0
app.secrets.storage.secret-key=1e238bf0507ad29e7e66ad654d0ad51c063014c6cbf0bd182348490fdfd1e818
app.secrets.storage.region=us-east-1
app.secrets.storage.bucket-name=english-learning-media
app.secrets.storage.endpoint=https://31efc9ffb5dd1f350db3956efcb0c9f6.r2.cloudflarestorage.com

# Google Gemini AI Key
app.secrets.gemini.api-key=AQ.Ab8RN6KPDlXPquRZkDHxnmvVNr-cEl-rXhQMBV3j_2aaCGj0CQ
app.secrets.gemini.base-url=https://generativelanguage.googleapis.com/v1beta
app.secrets.gemini.model=gemini-2.5-flash